### ISSUE TITLE
stylowanie

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Kanban#1]
jest super, ostyluj tylko te klase `.card-placeholder` (ktora masz juz dodana w js w konfiguracji `sortable`) zeby bylo widac w jakie miejsce przeciagasz karte

**Comment by michal-bootcamp** [comment]
jak pojawia sie element z klasa `card-placeholder`, to jest pusty i ma zerowa wysokosc, dodaj mu oprocz backgroundu jakas `min-height`

**Comment by JoannaKu** [comment]
zrobione :)
